name = "match-consumer"
main = "src/worker.ts"
compatibility_date = "2023-05-31"

# # KV Namespace binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# # Durable Object binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
# [[durable_objects]]
# binding = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# # Bucket binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv#bucket
# [[buckets]]
# binding = "MY_BUCKET"
# name = "my-bucket"
# bucket_id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

# # Service binding - For more information: https://developers.cloudflare.com/workers/platform/services
# [[routes]]
# binding = "MY_SERVICE"
# pattern = "/api/*"
# script = "api.js"

# # Queue binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/queues
# [[queues]]
# binding = "MY_QUEUE"
# name = "my-queue"
# zone_id = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"

[[queues.consumers]]
queue = "new-match-consumer"
max_batch_size = 10 # optional: defaults to 10
max_batch_timeout = 5 # optional: defaults to 5 seconds

[[d1_databases]]
binding = "MATCH_STATS_DB"
database_name = "match-stats"
database_id = "9d670caa-3af1-49b9-9b0d-91fe4b1cc21c"

# [env.production]
# MY_VARIABLE = "production_value"

# [env.staging]
# MY_VARIABLE = "staging_value"

# [env.shared]
# SHARED_VARIABLE = "shared_value"

[triggers]
crons = ["0 9 * * 1,5"]